#ifdef __CLING__
#pragma cling optimize(0)
#endif
void plot_fig_7_a()
{
   gROOT->SetBatch(kTRUE);
//=========Macro generated from canvas: c4/Diphoton rapidity
//=========  (Sun Mar 31 15:01:59 2024) by ROOT version 6.28/06
   TCanvas *c4 = new TCanvas("c4", "Diphoton rapidity",50,78,600,670);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c4->Range(0,0,1,1);
   c4->SetFillColor(0);
   c4->SetBorderMode(0);
   c4->SetBorderSize(2);
   c4->SetLeftMargin(0.18);
   c4->SetRightMargin(0.04);
   c4->SetTopMargin(0.08);
   c4->SetBottomMargin(0.18);
   c4->SetFrameFillStyle(0);
   c4->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: pad9
   TPad *pad9 = new TPad("pad9", "pad9",0,0.3,1,1);
   pad9->Draw();
   pad9->cd();
   pad9->Range(-3.126316,-1.129568,2.663158,65.31561);
   pad9->SetFillColor(0);
   pad9->SetBorderMode(0);
   pad9->SetBorderSize(2);
   pad9->SetTickx(1);
   pad9->SetTicky(1);
   pad9->SetLeftMargin(0.16);
   pad9->SetRightMargin(0.08);
   pad9->SetTopMargin(0.08);
   pad9->SetBottomMargin(0.017);
   pad9->SetFrameFillStyle(0);
   pad9->SetFrameBorderMode(0);
   pad9->SetFrameFillStyle(0);
   pad9->SetFrameBorderMode(0);
   
   TH1D *hUnfoDataRap_xSec__1 = new TH1D("hUnfoDataRap_xSec__1","",3,-2.2,2.2);
   hUnfoDataRap_xSec__1->SetBinContent(1,27.6834);
   hUnfoDataRap_xSec__1->SetBinContent(2,27.7743);
   hUnfoDataRap_xSec__1->SetBinContent(3,17.49684);
   hUnfoDataRap_xSec__1->SetBinError(1,6.644016);
   hUnfoDataRap_xSec__1->SetBinError(2,6.665832);
   hUnfoDataRap_xSec__1->SetBinError(3,4.199242);
   hUnfoDataRap_xSec__1->SetMinimum(0);
   hUnfoDataRap_xSec__1->SetMaximum(60);
   hUnfoDataRap_xSec__1->SetEntries(3);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = 1179;
   color = new TColor(ci, 0, 0, 0, " ", 0.5);
   hUnfoDataRap_xSec__1->SetFillColor(ci);
   hUnfoDataRap_xSec__1->SetFillStyle(3005);
   hUnfoDataRap_xSec__1->SetLineWidth(2);
   hUnfoDataRap_xSec__1->SetMarkerStyle(20);
   hUnfoDataRap_xSec__1->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__1->GetXaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__1->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__1->GetXaxis()->SetLabelSize(0);
   hUnfoDataRap_xSec__1->GetXaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__1->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__1->GetXaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__1->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hUnfoDataRap_xSec__1->GetYaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__1->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__1->GetYaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__1->GetYaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__1->GetYaxis()->SetTitleOffset(1.1);
   hUnfoDataRap_xSec__1->GetYaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__1->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__1->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__1->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__1->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__1->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__1->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__1->Draw("e2");
   
   TH1D *hUnfoDataRap_xSec__2 = new TH1D("hUnfoDataRap_xSec__2","",3,-2.2,2.2);
   hUnfoDataRap_xSec__2->SetBinContent(1,27.6834);
   hUnfoDataRap_xSec__2->SetBinContent(2,27.7743);
   hUnfoDataRap_xSec__2->SetBinContent(3,17.49684);
   hUnfoDataRap_xSec__2->SetBinError(1,18.53016);
   hUnfoDataRap_xSec__2->SetBinError(2,14.06935);
   hUnfoDataRap_xSec__2->SetBinError(3,16.15609);
   hUnfoDataRap_xSec__2->SetMinimum(0);
   hUnfoDataRap_xSec__2->SetMaximum(60);
   hUnfoDataRap_xSec__2->SetEntries(3);
   hUnfoDataRap_xSec__2->SetLineWidth(2);
   hUnfoDataRap_xSec__2->SetMarkerStyle(20);
   hUnfoDataRap_xSec__2->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__2->GetXaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__2->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__2->GetXaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__2->GetXaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__2->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__2->GetXaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__2->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hUnfoDataRap_xSec__2->GetYaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__2->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__2->GetYaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__2->GetYaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__2->GetYaxis()->SetTitleOffset(1.1);
   hUnfoDataRap_xSec__2->GetYaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__2->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__2->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__2->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__2->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__2->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__2->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__2->Draw("psameex0");
   
   TH1D *hGenRap_xSec__3 = new TH1D("hGenRap_xSec__3","",3,-2.2,2.2);
   hGenRap_xSec__3->SetBinContent(1,15.90076);
   hGenRap_xSec__3->SetBinContent(2,32.48363);
   hGenRap_xSec__3->SetBinContent(3,15.07844);
   hGenRap_xSec__3->SetBinError(1,0.245471);
   hGenRap_xSec__3->SetBinError(2,0.3508516);
   hGenRap_xSec__3->SetBinError(3,0.2390393);
   hGenRap_xSec__3->SetEntries(3);

   ci = TColor::GetColor("#009999");
   hGenRap_xSec__3->SetLineColor(ci);
   hGenRap_xSec__3->SetLineWidth(2);

   ci = TColor::GetColor("#009999");
   hGenRap_xSec__3->SetMarkerColor(ci);
   hGenRap_xSec__3->SetMarkerStyle(2);
   hGenRap_xSec__3->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hGenRap_xSec__3->GetXaxis()->SetLabelFont(42);
   hGenRap_xSec__3->GetXaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__3->GetXaxis()->SetLabelSize(0.05);
   hGenRap_xSec__3->GetXaxis()->SetTitleSize(0.06);
   hGenRap_xSec__3->GetXaxis()->SetTitleOffset(1);
   hGenRap_xSec__3->GetXaxis()->SetTitleFont(42);
   hGenRap_xSec__3->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hGenRap_xSec__3->GetYaxis()->SetLabelFont(42);
   hGenRap_xSec__3->GetYaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__3->GetYaxis()->SetLabelSize(0.05);
   hGenRap_xSec__3->GetYaxis()->SetTitleSize(0.06);
   hGenRap_xSec__3->GetYaxis()->SetTitleOffset(1.1);
   hGenRap_xSec__3->GetYaxis()->SetTitleFont(42);
   hGenRap_xSec__3->GetZaxis()->SetLabelFont(42);
   hGenRap_xSec__3->GetZaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__3->GetZaxis()->SetLabelSize(0.05);
   hGenRap_xSec__3->GetZaxis()->SetTitleSize(0.06);
   hGenRap_xSec__3->GetZaxis()->SetTitleOffset(1);
   hGenRap_xSec__3->GetZaxis()->SetTitleFont(42);
   hGenRap_xSec__3->Draw("histsame");
   
   TH1D *hGenRap_xSec__4 = new TH1D("hGenRap_xSec__4","",3,-2.2,2.2);
   hGenRap_xSec__4->SetBinContent(1,15.90076);
   hGenRap_xSec__4->SetBinContent(2,32.48363);
   hGenRap_xSec__4->SetBinContent(3,15.07844);
   hGenRap_xSec__4->SetBinError(1,0.245471);
   hGenRap_xSec__4->SetBinError(2,0.3508516);
   hGenRap_xSec__4->SetBinError(3,0.2390393);
   hGenRap_xSec__4->SetEntries(3);

   ci = TColor::GetColor("#009999");
   hGenRap_xSec__4->SetLineColor(ci);
   hGenRap_xSec__4->SetLineWidth(2);

   ci = TColor::GetColor("#009999");
   hGenRap_xSec__4->SetMarkerColor(ci);
   hGenRap_xSec__4->SetMarkerStyle(2);
   hGenRap_xSec__4->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hGenRap_xSec__4->GetXaxis()->SetLabelFont(42);
   hGenRap_xSec__4->GetXaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__4->GetXaxis()->SetLabelSize(0.05);
   hGenRap_xSec__4->GetXaxis()->SetTitleSize(0.06);
   hGenRap_xSec__4->GetXaxis()->SetTitleOffset(1);
   hGenRap_xSec__4->GetXaxis()->SetTitleFont(42);
   hGenRap_xSec__4->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hGenRap_xSec__4->GetYaxis()->SetLabelFont(42);
   hGenRap_xSec__4->GetYaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__4->GetYaxis()->SetLabelSize(0.05);
   hGenRap_xSec__4->GetYaxis()->SetTitleSize(0.06);
   hGenRap_xSec__4->GetYaxis()->SetTitleOffset(1.1);
   hGenRap_xSec__4->GetYaxis()->SetTitleFont(42);
   hGenRap_xSec__4->GetZaxis()->SetLabelFont(42);
   hGenRap_xSec__4->GetZaxis()->SetLabelOffset(0.007);
   hGenRap_xSec__4->GetZaxis()->SetLabelSize(0.05);
   hGenRap_xSec__4->GetZaxis()->SetTitleSize(0.06);
   hGenRap_xSec__4->GetZaxis()->SetTitleOffset(1);
   hGenRap_xSec__4->GetZaxis()->SetTitleFont(42);
   hGenRap_xSec__4->Draw("psameex0");
   
   TH1D *hUnfoDataRap_xSec__5 = new TH1D("hUnfoDataRap_xSec__5","",3,-2.2,2.2);
   hUnfoDataRap_xSec__5->SetBinContent(1,27.6834);
   hUnfoDataRap_xSec__5->SetBinContent(2,27.7743);
   hUnfoDataRap_xSec__5->SetBinContent(3,17.49684);
   hUnfoDataRap_xSec__5->SetBinError(1,18.53016);
   hUnfoDataRap_xSec__5->SetBinError(2,14.06935);
   hUnfoDataRap_xSec__5->SetBinError(3,16.15609);
   hUnfoDataRap_xSec__5->SetMinimum(0);
   hUnfoDataRap_xSec__5->SetMaximum(60);
   hUnfoDataRap_xSec__5->SetEntries(3);
   hUnfoDataRap_xSec__5->SetLineWidth(2);
   hUnfoDataRap_xSec__5->SetMarkerStyle(20);
   hUnfoDataRap_xSec__5->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__5->GetXaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__5->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__5->GetXaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__5->GetXaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__5->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__5->GetXaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__5->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hUnfoDataRap_xSec__5->GetYaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__5->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__5->GetYaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__5->GetYaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__5->GetYaxis()->SetTitleOffset(1.1);
   hUnfoDataRap_xSec__5->GetYaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__5->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__5->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__5->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__5->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__5->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__5->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__5->Draw("psameex0");
   Double_t xAxis1[4] = {-2.2, -0.7333333, 0.7333333, 2.2}; 
   
   TH1F *hgammaUPC_LbL_Rap__6 = new TH1F("hgammaUPC_LbL_Rap__6","d#sigma/dy (pb) photon pairs (after cuts) [LbL]",3, xAxis1);
   hgammaUPC_LbL_Rap__6->SetBinContent(1,14.57033);
   hgammaUPC_LbL_Rap__6->SetBinContent(2,35.85674);
   hgammaUPC_LbL_Rap__6->SetBinContent(3,14.60553);
   hgammaUPC_LbL_Rap__6->SetBinError(1,0.04861452);
   hgammaUPC_LbL_Rap__6->SetBinError(2,0.07626349);
   hgammaUPC_LbL_Rap__6->SetBinError(3,0.04867321);
   hgammaUPC_LbL_Rap__6->SetEntries(400930);

   ci = TColor::GetColor("#000099");
   hgammaUPC_LbL_Rap__6->SetLineColor(ci);
   hgammaUPC_LbL_Rap__6->SetLineWidth(2);

   ci = TColor::GetColor("#000099");
   hgammaUPC_LbL_Rap__6->SetMarkerColor(ci);
   hgammaUPC_LbL_Rap__6->SetMarkerStyle(2);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetRange(1,100);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetTitleOffset(1);
   hgammaUPC_LbL_Rap__6->GetXaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetTitleOffset(1.1);
   hgammaUPC_LbL_Rap__6->GetYaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetTitleOffset(1);
   hgammaUPC_LbL_Rap__6->GetZaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__6->Draw("histsame");
   Double_t xAxis2[4] = {-2.2, -0.7333333, 0.7333333, 2.2}; 
   
   TH1F *hgammaUPC_LbL_Rap__7 = new TH1F("hgammaUPC_LbL_Rap__7","d#sigma/dy (pb) photon pairs (after cuts) [LbL]",3, xAxis2);
   hgammaUPC_LbL_Rap__7->SetBinContent(1,14.57033);
   hgammaUPC_LbL_Rap__7->SetBinContent(2,35.85674);
   hgammaUPC_LbL_Rap__7->SetBinContent(3,14.60553);
   hgammaUPC_LbL_Rap__7->SetBinError(1,0.04861452);
   hgammaUPC_LbL_Rap__7->SetBinError(2,0.07626349);
   hgammaUPC_LbL_Rap__7->SetBinError(3,0.04867321);
   hgammaUPC_LbL_Rap__7->SetEntries(400930);

   ci = TColor::GetColor("#000099");
   hgammaUPC_LbL_Rap__7->SetLineColor(ci);
   hgammaUPC_LbL_Rap__7->SetLineWidth(2);

   ci = TColor::GetColor("#000099");
   hgammaUPC_LbL_Rap__7->SetMarkerColor(ci);
   hgammaUPC_LbL_Rap__7->SetMarkerStyle(2);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetRange(1,100);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetTitleOffset(1);
   hgammaUPC_LbL_Rap__7->GetXaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetTitleOffset(1.1);
   hgammaUPC_LbL_Rap__7->GetYaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetLabelFont(42);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetLabelOffset(0.007);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetLabelSize(0.05);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetTitleSize(0.06);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetTitleOffset(1);
   hgammaUPC_LbL_Rap__7->GetZaxis()->SetTitleFont(42);
   hgammaUPC_LbL_Rap__7->Draw("psamex0");
   
   TLegend *leg = new TLegend(0.4,0.68,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(43);
   leg->SetTextSize(20);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#gamma#gamma#rightarrow #gamma#gamma","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("hUnfoDataRap_xSec","Data ","EP");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("hUnfoDataRap_xSec","gamma-UPC@NLO","pl");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#000099");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   entry=leg->AddEntry("hUnfoDataRap_xSec","SUPERCHIC","pl");

   ci = TColor::GetColor("#009999");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);

   ci = TColor::GetColor("#009999");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(43);
   leg->Draw();
   pad9->Modified();
   c4->cd();
   TLatex *   tex = new TLatex(0.16,0.96,"#bf{CMS} #it{Preliminary}");
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.52,0.96,"#scale[0.8]{PbPb, 1.64 nb^{-1} (#sqrt{s_{NN}} = 5.02 TeV)}");
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
  
// ------------>Primitives in pad: pad10
   TPad *pad10 = new TPad("pad10", "pad10",0,0.06,1,0.28);
   pad10->Draw();
   pad10->cd();
   pad10->Range(-3.126316,-2.683896,2.663158,3.280318);
   pad10->SetFillColor(0);
   pad10->SetBorderMode(0);
   pad10->SetBorderSize(2);
   pad10->SetTickx(1);
   pad10->SetTicky(1);
   pad10->SetLeftMargin(0.16);
   pad10->SetRightMargin(0.08);
   pad10->SetTopMargin(0.047);
   pad10->SetBottomMargin(0.45);
   pad10->SetFrameFillStyle(0);
   pad10->SetFrameBorderMode(0);
   pad10->SetFrameFillStyle(0);
   pad10->SetFrameBorderMode(0);
   
   TH1D *hUnfoDataRap_xSec__8 = new TH1D("hUnfoDataRap_xSec__8","",3,-2.2,2.2);
   hUnfoDataRap_xSec__8->SetBinContent(1,1.741011);
   hUnfoDataRap_xSec__8->SetBinContent(2,0.8550244);
   hUnfoDataRap_xSec__8->SetBinContent(3,1.160388);
   hUnfoDataRap_xSec__8->SetBinError(1,1.165673);
   hUnfoDataRap_xSec__8->SetBinError(2,0.4332197);
   hUnfoDataRap_xSec__8->SetBinError(3,1.071628);
   hUnfoDataRap_xSec__8->SetMinimum(0);
   hUnfoDataRap_xSec__8->SetMaximum(3);
   hUnfoDataRap_xSec__8->SetEntries(5.236163);

   ci = TColor::GetColor("#009999");
   hUnfoDataRap_xSec__8->SetLineColor(ci);
   hUnfoDataRap_xSec__8->SetLineWidth(2);

   ci = TColor::GetColor("#009999");
   hUnfoDataRap_xSec__8->SetMarkerColor(ci);
   hUnfoDataRap_xSec__8->SetMarkerStyle(20);
   hUnfoDataRap_xSec__8->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__8->GetXaxis()->SetLabelFont(43);
   hUnfoDataRap_xSec__8->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__8->GetXaxis()->SetLabelSize(20);
   hUnfoDataRap_xSec__8->GetXaxis()->SetTitleSize(20);
   hUnfoDataRap_xSec__8->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__8->GetXaxis()->SetTitleFont(43);
   hUnfoDataRap_xSec__8->GetYaxis()->SetTitle("#frac{Data}{Exp.}");
   hUnfoDataRap_xSec__8->GetYaxis()->SetNdivisions(5);
   hUnfoDataRap_xSec__8->GetYaxis()->SetLabelFont(43);
   hUnfoDataRap_xSec__8->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__8->GetYaxis()->SetLabelSize(20);
   hUnfoDataRap_xSec__8->GetYaxis()->SetTitleSize(22);
   hUnfoDataRap_xSec__8->GetYaxis()->SetTitleOffset(2);
   hUnfoDataRap_xSec__8->GetYaxis()->SetTitleFont(43);
   hUnfoDataRap_xSec__8->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__8->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__8->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__8->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__8->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__8->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__8->Draw("pex0");
   
   TH1D *hUnfoDataRap_xSec__9 = new TH1D("hUnfoDataRap_xSec__9","",3,-2.2,2.2);
   hUnfoDataRap_xSec__9->SetBinContent(1,1.899984);
   hUnfoDataRap_xSec__9->SetBinContent(2,0.7745908);
   hUnfoDataRap_xSec__9->SetBinContent(3,1.19796);
   hUnfoDataRap_xSec__9->SetBinError(1,1.271789);
   hUnfoDataRap_xSec__9->SetBinError(2,0.3923803);
   hUnfoDataRap_xSec__9->SetBinError(3,1.10617);
   hUnfoDataRap_xSec__9->SetMinimum(0);
   hUnfoDataRap_xSec__9->SetMaximum(4);
   hUnfoDataRap_xSec__9->SetEntries(5.007153);

   ci = TColor::GetColor("#000099");
   hUnfoDataRap_xSec__9->SetLineColor(ci);
   hUnfoDataRap_xSec__9->SetLineWidth(2);

   ci = TColor::GetColor("#000099");
   hUnfoDataRap_xSec__9->SetMarkerColor(ci);
   hUnfoDataRap_xSec__9->SetMarkerStyle(22);
   hUnfoDataRap_xSec__9->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__9->GetXaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__9->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__9->GetXaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__9->GetXaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__9->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__9->GetXaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__9->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hUnfoDataRap_xSec__9->GetYaxis()->SetNdivisions(5);
   hUnfoDataRap_xSec__9->GetYaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__9->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__9->GetYaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__9->GetYaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__9->GetYaxis()->SetTitleOffset(1.1);
   hUnfoDataRap_xSec__9->GetYaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__9->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__9->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__9->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__9->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__9->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__9->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__9->Draw("pex0same");
   
   TH1D *hUnfoDataRap_xSec__10 = new TH1D("hUnfoDataRap_xSec__10","",3,-2.2,2.2);
   hUnfoDataRap_xSec__10->SetBinContent(1,1);
   hUnfoDataRap_xSec__10->SetBinContent(2,1);
   hUnfoDataRap_xSec__10->SetBinContent(3,1);
   hUnfoDataRap_xSec__10->SetBinError(1,0.3394113);
   hUnfoDataRap_xSec__10->SetBinError(2,0.3394113);
   hUnfoDataRap_xSec__10->SetBinError(3,0.3394113);
   hUnfoDataRap_xSec__10->SetMinimum(0);
   hUnfoDataRap_xSec__10->SetMaximum(60);
   hUnfoDataRap_xSec__10->SetEntries(26.04167);

   ci = 1179;
   color = new TColor(ci, 0, 0, 0, " ", 0.5);
   hUnfoDataRap_xSec__10->SetFillColor(ci);
   hUnfoDataRap_xSec__10->SetFillStyle(3005);

   ci = TColor::GetColor("#009999");
   hUnfoDataRap_xSec__10->SetLineColor(ci);
   hUnfoDataRap_xSec__10->SetLineStyle(2);
   hUnfoDataRap_xSec__10->SetLineWidth(2);

   ci = TColor::GetColor("#009999");
   hUnfoDataRap_xSec__10->SetMarkerColor(ci);
   hUnfoDataRap_xSec__10->SetMarkerStyle(0);
   hUnfoDataRap_xSec__10->GetXaxis()->SetTitle("y^{#gamma#gamma}");
   hUnfoDataRap_xSec__10->GetXaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__10->GetXaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__10->GetXaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__10->GetXaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__10->GetXaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__10->GetXaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__10->GetYaxis()->SetTitle("#frac{d#sigma^{#gamma#gamma}}{dy^{#gamma#gamma}} (nb / 0.733)");
   hUnfoDataRap_xSec__10->GetYaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__10->GetYaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__10->GetYaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__10->GetYaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__10->GetYaxis()->SetTitleOffset(1.1);
   hUnfoDataRap_xSec__10->GetYaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__10->GetZaxis()->SetLabelFont(42);
   hUnfoDataRap_xSec__10->GetZaxis()->SetLabelOffset(0.007);
   hUnfoDataRap_xSec__10->GetZaxis()->SetLabelSize(0.05);
   hUnfoDataRap_xSec__10->GetZaxis()->SetTitleSize(0.06);
   hUnfoDataRap_xSec__10->GetZaxis()->SetTitleOffset(1);
   hUnfoDataRap_xSec__10->GetZaxis()->SetTitleFont(42);
   hUnfoDataRap_xSec__10->Draw("e2same");
   
   TF1 *line1 = new TF1("line","1",-100,100, TF1::EAddToList::kDefault);
   line1->SetFillColor(19);
   line1->SetFillStyle(0);
   line1->SetMarkerStyle(20);
   line1->SetLineStyle(2);
   line1->SetLineWidth(1);
   line1->GetXaxis()->SetLabelFont(42);
   line1->GetXaxis()->SetLabelOffset(0.007);
   line1->GetXaxis()->SetLabelSize(0.05);
   line1->GetXaxis()->SetTitleSize(0.06);
   line1->GetXaxis()->SetTitleOffset(0.9);
   line1->GetXaxis()->SetTitleFont(42);
   line1->GetYaxis()->SetLabelFont(42);
   line1->GetYaxis()->SetLabelOffset(0.007);
   line1->GetYaxis()->SetLabelSize(0.05);
   line1->GetYaxis()->SetTitleSize(0.06);
   line1->GetYaxis()->SetTitleOffset(1);
   line1->GetYaxis()->SetTitleFont(42);
   line1->Draw("same");
   pad10->Modified();
   c4->cd();
   c4->Modified();
   c4->cd();
   c4->SetSelected(c4);
   c4->SaveAs("Figure_007_a.pdf");
}
