#ifdef __CLING__
#pragma cling optimize(0)
#endif

#include "style.h"

void plot_fig_6_e() {
  gROOT->SetBatch(kTRUE);
  //=========Macro generated from canvas: goodPhotonSR_phi/goodPhotonSR_phi
  //=========  (Sun Mar 31 12:51:37 2024) by ROOT version 6.26/08
  TCanvas *goodPhotonSR_phi = new TCanvas("goodPhotonSR_phi", "goodPhotonSR_phi", 0, 0, 800, 600);
  gStyle->SetOptFit(1);
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  goodPhotonSR_phi->SetHighLightColor(2);
  goodPhotonSR_phi->Range(0, 0, 1, 1);
  goodPhotonSR_phi->SetFillColor(0);
  goodPhotonSR_phi->SetBorderMode(0);
  goodPhotonSR_phi->SetBorderSize(2);
  goodPhotonSR_phi->SetTickx(1);
  goodPhotonSR_phi->SetTicky(1);
  goodPhotonSR_phi->SetLeftMargin(0.16);
  goodPhotonSR_phi->SetRightMargin(0.15);
  goodPhotonSR_phi->SetTopMargin(0.06);
  goodPhotonSR_phi->SetBottomMargin(0.3);
  goodPhotonSR_phi->SetFrameFillStyle(0);
  goodPhotonSR_phi->SetFrameBorderMode(0);

  // ------------>Primitives in pad: goodPhotonSR_phi_1
  TPad *goodPhotonSR_phi_1 = new TPad("goodPhotonSR_phi_1", "goodPhotonSR_phi_1", 0, 0.3, 1, 1);
  goodPhotonSR_phi_1->Draw();
  goodPhotonSR_phi_1->cd();
  goodPhotonSR_phi_1->Range(-4.596232, 0, 4.505217, 21.97802);
  goodPhotonSR_phi_1->SetFillColor(0);
  goodPhotonSR_phi_1->SetBorderMode(0);
  goodPhotonSR_phi_1->SetBorderSize(2);
  goodPhotonSR_phi_1->SetLeftMargin(0.16);
  goodPhotonSR_phi_1->SetRightMargin(0.15);
  goodPhotonSR_phi_1->SetBottomMargin(0.05);
  goodPhotonSR_phi_1->SetFrameFillStyle(0);
  goodPhotonSR_phi_1->SetFrameBorderMode(0);
  goodPhotonSR_phi_1->SetFrameFillStyle(0);
  goodPhotonSR_phi_1->SetFrameLineWidth(2);
  goodPhotonSR_phi_1->SetFrameBorderMode(0);
  goodPhotonSR_phi_1->SetFrameBorderSize(2);

  THStack *goodPhotonSR_phibackground = new THStack();
  goodPhotonSR_phibackground->SetName("goodPhotonSR_phibackground");
  goodPhotonSR_phibackground->SetTitle("");
  goodPhotonSR_phibackground->SetMaximum(21);

  TH1F *goodPhotonSR_phibackground_stack_7 = new TH1F("goodPhotonSR_phibackground_stack_7", "", 6, -3.14, 3.14);
  goodPhotonSR_phibackground_stack_7->SetMinimum(0);
  goodPhotonSR_phibackground_stack_7->SetMaximum(21);
  goodPhotonSR_phibackground_stack_7->SetDirectory(0);
  goodPhotonSR_phibackground_stack_7->SetStats(0);
  goodPhotonSR_phibackground_stack_7->SetLineStyle(0);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetTitle("#phi^{#gamma}");
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetLabelSize(0.0);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetTitleSize(fig_6_x_title_size);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetTitleOffset(1.7);
  goodPhotonSR_phibackground_stack_7->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetTitle("Entries / 1.05");
  goodPhotonSR_phibackground_stack_7->GetYaxis()->CenterTitle(true);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetNdivisions(505);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetLabelSize(0.06);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetTitleSize(fig_6_y_title_size);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetTitleOffset(1.0);
  goodPhotonSR_phibackground_stack_7->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetLabelSize(0.05);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetTitleSize(0.06);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phibackground_stack_7->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground->SetHistogram(goodPhotonSR_phibackground_stack_7);

  TH1D *goodPhotonSR_phi_stack_1 = new TH1D("goodPhotonSR_phi_stack_1", "goodPhotonSR_phi", 6, -3.14, 3.14);
  goodPhotonSR_phi_stack_1->SetBinContent(0, 0.002471202);
  goodPhotonSR_phi_stack_1->SetBinContent(1, 3.464625);
  goodPhotonSR_phi_stack_1->SetBinContent(2, 3.281756);
  goodPhotonSR_phi_stack_1->SetBinContent(3, 3.343536);
  goodPhotonSR_phi_stack_1->SetBinContent(4, 3.472038);
  goodPhotonSR_phi_stack_1->SetBinContent(5, 3.296583);
  goodPhotonSR_phi_stack_1->SetBinContent(6, 3.346007);
  goodPhotonSR_phi_stack_1->SetBinContent(7, 0.002471202);
  goodPhotonSR_phi_stack_1->SetBinError(0, 0.002471202);
  goodPhotonSR_phi_stack_1->SetBinError(1, 0.09252992);
  goodPhotonSR_phi_stack_1->SetBinError(2, 0.09005488);
  goodPhotonSR_phi_stack_1->SetBinError(3, 0.09089858);
  goodPhotonSR_phi_stack_1->SetBinError(4, 0.09262887);
  goodPhotonSR_phi_stack_1->SetBinError(5, 0.09025808);
  goodPhotonSR_phi_stack_1->SetBinError(6, 0.09093216);
  goodPhotonSR_phi_stack_1->SetBinError(7, 0.002471202);
  goodPhotonSR_phi_stack_1->SetEntries(8178);
  goodPhotonSR_phi_stack_1->SetDirectory(0);

  Int_t ci;       // for color index setting
  TColor *color;  // for color definition with alpha
  ci = TColor::GetColor("#6699ff");
  goodPhotonSR_phi_stack_1->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  goodPhotonSR_phi_stack_1->SetLineColor(ci);
  goodPhotonSR_phi_stack_1->SetMarkerStyle(20);
  goodPhotonSR_phi_stack_1->GetXaxis()->SetRange(1, 6);
  goodPhotonSR_phi_stack_1->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_1->GetXaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_1->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_1->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_1->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_1->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_1->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_1->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground->Add(goodPhotonSR_phi_stack_1, "");

  TH1D *goodPhotonSR_phi_stack_2 = new TH1D("goodPhotonSR_phi_stack_2", "goodPhotonSR_phi", 6, -3.14, 3.14);
  goodPhotonSR_phi_stack_2->SetBinContent(1, 0.1724906);
  goodPhotonSR_phi_stack_2->SetBinContent(2, 0.2299875);
  goodPhotonSR_phi_stack_2->SetBinContent(3, 0.3449812);
  goodPhotonSR_phi_stack_2->SetBinContent(4, 0.1724906);
  goodPhotonSR_phi_stack_2->SetBinContent(5, 0.2299875);
  goodPhotonSR_phi_stack_2->SetBinContent(6, 0.3449812);
  goodPhotonSR_phi_stack_2->SetBinError(1, 0.09958751);
  goodPhotonSR_phi_stack_2->SetBinError(2, 0.1149937);
  goodPhotonSR_phi_stack_2->SetBinError(3, 0.140838);
  goodPhotonSR_phi_stack_2->SetBinError(4, 0.09958751);
  goodPhotonSR_phi_stack_2->SetBinError(5, 0.1149937);
  goodPhotonSR_phi_stack_2->SetBinError(6, 0.140838);
  goodPhotonSR_phi_stack_2->SetEntries(26);
  goodPhotonSR_phi_stack_2->SetDirectory(0);

  ci = TColor::GetColor("#ffff00");
  goodPhotonSR_phi_stack_2->SetFillColor(ci);

  ci = TColor::GetColor("#ffff00");
  goodPhotonSR_phi_stack_2->SetLineColor(ci);
  goodPhotonSR_phi_stack_2->SetMarkerStyle(20);
  goodPhotonSR_phi_stack_2->SetMarkerSize(0);
  goodPhotonSR_phi_stack_2->GetXaxis()->SetRange(1, 6);
  goodPhotonSR_phi_stack_2->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_2->GetXaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_2->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_2->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_2->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_2->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_2->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_2->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground->Add(goodPhotonSR_phi_stack_2, "");

  TH1D *goodPhotonSR_phi_stack_3 = new TH1D("goodPhotonSR_phi_stack_3", "goodPhotonSR_phi", 6, -3.14, 3.14);
  goodPhotonSR_phi_stack_3->SetBinContent(1, 0.3609131);
  goodPhotonSR_phi_stack_3->SetBinContent(2, 0.5774609);
  goodPhotonSR_phi_stack_3->SetBinContent(3, 0.2165479);
  goodPhotonSR_phi_stack_3->SetBinContent(4, 0.3609131);
  goodPhotonSR_phi_stack_3->SetBinContent(5, 0.5774609);
  goodPhotonSR_phi_stack_3->SetBinContent(6, 0.2165479);
  goodPhotonSR_phi_stack_3->SetBinError(1, 0.1614052);
  goodPhotonSR_phi_stack_3->SetBinError(2, 0.2041633);
  goodPhotonSR_phi_stack_3->SetBinError(3, 0.125024);
  goodPhotonSR_phi_stack_3->SetBinError(4, 0.1614052);
  goodPhotonSR_phi_stack_3->SetBinError(5, 0.2041633);
  goodPhotonSR_phi_stack_3->SetBinError(6, 0.125024);
  goodPhotonSR_phi_stack_3->SetEntries(32);
  goodPhotonSR_phi_stack_3->SetDirectory(0);

  ci = TColor::GetColor("#ffff00");
  goodPhotonSR_phi_stack_3->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  goodPhotonSR_phi_stack_3->SetLineColor(ci);
  goodPhotonSR_phi_stack_3->SetMarkerStyle(20);
  goodPhotonSR_phi_stack_3->SetMarkerSize(0);
  goodPhotonSR_phi_stack_3->GetXaxis()->SetRange(1, 6);
  goodPhotonSR_phi_stack_3->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_3->GetXaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_3->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_3->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_3->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_3->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_3->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_3->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground->Add(goodPhotonSR_phi_stack_3, "");

  TH1D *goodPhotonSR_phi_stack_4 = new TH1D("goodPhotonSR_phi_stack_4", "goodPhotonSR_phi", 6, -3.14, 3.14);
  goodPhotonSR_phi_stack_4->SetBinContent(0, 0.005655923);
  goodPhotonSR_phi_stack_4->SetBinContent(1, 4.439899);
  goodPhotonSR_phi_stack_4->SetBinContent(2, 4.117512);
  goodPhotonSR_phi_stack_4->SetBinContent(3, 4.25891);
  goodPhotonSR_phi_stack_4->SetBinContent(4, 4.434243);
  goodPhotonSR_phi_stack_4->SetBinContent(5, 4.111856);
  goodPhotonSR_phi_stack_4->SetBinContent(6, 4.253254);
  goodPhotonSR_phi_stack_4->SetBinContent(7, 0.02262369);
  goodPhotonSR_phi_stack_4->SetBinError(0, 0.005655923);
  goodPhotonSR_phi_stack_4->SetBinError(1, 0.1584668);
  goodPhotonSR_phi_stack_4->SetBinError(2, 0.1526051);
  goodPhotonSR_phi_stack_4->SetBinError(3, 0.1552033);
  goodPhotonSR_phi_stack_4->SetBinError(4, 0.1583658);
  goodPhotonSR_phi_stack_4->SetBinError(5, 0.1525003);
  goodPhotonSR_phi_stack_4->SetBinError(6, 0.1551002);
  goodPhotonSR_phi_stack_4->SetBinError(7, 0.01131185);
  goodPhotonSR_phi_stack_4->SetEntries(4534);
  goodPhotonSR_phi_stack_4->SetDirectory(0);

  ci = TColor::GetColor("#ff9933");
  goodPhotonSR_phi_stack_4->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  goodPhotonSR_phi_stack_4->SetLineColor(ci);
  goodPhotonSR_phi_stack_4->SetMarkerStyle(20);
  goodPhotonSR_phi_stack_4->GetXaxis()->SetRange(1, 6);
  goodPhotonSR_phi_stack_4->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_4->GetXaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_4->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_4->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_4->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phi_stack_4->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phi_stack_4->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phi_stack_4->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground->Add(goodPhotonSR_phi_stack_4, "");
  goodPhotonSR_phibackground->Draw("hist");

  Double_t Graph0_fx3003[6] = {-2.616667, -1.57, -0.5233334, 0.5233334, 1.57, 2.616667};
  Double_t Graph0_fy3003[6] = {10, 8, 8, 10, 8, 8};
  Double_t Graph0_felx3003[6] = {0.5233334, 0.5233334, 0.5233334, 0.5233334, 0.5233334, 0.5233334};
  Double_t Graph0_fely3003[6] = {3.108694, 2.768386, 2.768386, 3.108694, 2.768386, 2.768386};
  Double_t Graph0_fehx3003[6] = {0.5233334, 0.5233334, 0.5233334, 0.5233334, 0.5233334, 0.5233334};
  Double_t Graph0_fehy3003[6] = {4.26695, 3.945142, 3.945142, 4.26695, 3.945142, 3.945142};
  TGraphAsymmErrors *grae =
      new TGraphAsymmErrors(6, Graph0_fx3003, Graph0_fy3003, Graph0_felx3003, Graph0_fehx3003, Graph0_fely3003, Graph0_fehy3003);
  grae->SetName("Graph0");
  grae->SetTitle("Graph");
  grae->SetFillStyle(1000);
  grae->SetMarkerStyle(20);

  TH1F *Graph_Graph03003 = new TH1F("Graph_Graph03003", "Graph", 100, -3.14, 3.14);
  Graph_Graph03003->SetMinimum(4.32808);
  Graph_Graph03003->SetMaximum(15.17048);
  Graph_Graph03003->SetDirectory(0);
  Graph_Graph03003->SetStats(0);
  Graph_Graph03003->SetLineStyle(0);
  Graph_Graph03003->GetXaxis()->SetLabelFont(42);
  Graph_Graph03003->GetXaxis()->SetLabelOffset(0.007);
  Graph_Graph03003->GetXaxis()->SetLabelSize(0.05);
  Graph_Graph03003->GetXaxis()->SetTitleSize(0.06);
  Graph_Graph03003->GetXaxis()->SetTitleOffset(0.9);
  Graph_Graph03003->GetXaxis()->SetTitleFont(42);
  Graph_Graph03003->GetYaxis()->SetLabelFont(42);
  Graph_Graph03003->GetYaxis()->SetLabelOffset(0.007);
  Graph_Graph03003->GetYaxis()->SetLabelSize(0.05);
  Graph_Graph03003->GetYaxis()->SetTitleSize(0.06);
  Graph_Graph03003->GetYaxis()->SetTitleOffset(1.25);
  Graph_Graph03003->GetYaxis()->SetTitleFont(42);
  Graph_Graph03003->GetZaxis()->SetLabelFont(42);
  Graph_Graph03003->GetZaxis()->SetLabelOffset(0.007);
  Graph_Graph03003->GetZaxis()->SetLabelSize(0.05);
  Graph_Graph03003->GetZaxis()->SetTitleSize(0.06);
  Graph_Graph03003->GetZaxis()->SetTitleOffset(1);
  Graph_Graph03003->GetZaxis()->SetTitleFont(42);
  grae->SetHistogram(Graph_Graph03003);

  grae->Draw("pe");
  

  TH1D *backgrounds_unc_goodPhotonSR_phi__7 = new TH1D("backgrounds_unc_goodPhotonSR_phi__7", "goodPhotonSR_phi", 6, -3.14, 3.14);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(0, 0.008127124);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(1, 8.437928);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(2, 8.206716);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(3, 8.163975);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(4, 8.439686);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(5, 8.215887);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(6, 8.16079);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinContent(7, 0.02509489);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(0, 0.00617222);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(1, 1.958584);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(2, 1.910269);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(3, 1.895687);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(4, 1.958981);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(5, 1.912355);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(6, 1.894954);
  backgrounds_unc_goodPhotonSR_phi__7->SetBinError(7, 0.01157863);
  backgrounds_unc_goodPhotonSR_phi__7->SetEntries(12770);

  ci = 1557;
  color = new TColor(ci, 0, 0, 0, " ", 0.3);
  backgrounds_unc_goodPhotonSR_phi__7->SetFillColorAlpha(ci, 0.5);
  backgrounds_unc_goodPhotonSR_phi__7->SetFillStyle(3004);
  backgrounds_unc_goodPhotonSR_phi__7->SetMarkerStyle(20);
  backgrounds_unc_goodPhotonSR_phi__7->SetMarkerSize(0);
  backgrounds_unc_goodPhotonSR_phi__7->GetXaxis()->SetRange(1, 6);
  backgrounds_unc_goodPhotonSR_phi__7->GetXaxis()->SetLabelFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->GetXaxis()->SetTitleOffset(1);
  backgrounds_unc_goodPhotonSR_phi__7->GetXaxis()->SetTitleFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->GetYaxis()->SetLabelFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->GetYaxis()->SetTitleFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->GetZaxis()->SetLabelFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->GetZaxis()->SetTitleOffset(1);
  backgrounds_unc_goodPhotonSR_phi__7->GetZaxis()->SetTitleFont(42);
  backgrounds_unc_goodPhotonSR_phi__7->Draw("same e2");

  auto leg = get_lbl_legend();
  // leg->Draw();

  TH1F *goodPhotonSR_phibackground_copy__8 = new TH1F("goodPhotonSR_phibackground_copy__8", "", 6, -3.14, 3.14);
  goodPhotonSR_phibackground_copy__8->SetMinimum(0);
  goodPhotonSR_phibackground_copy__8->SetMaximum(21);
  goodPhotonSR_phibackground_copy__8->SetDirectory(0);
  goodPhotonSR_phibackground_copy__8->SetStats(0);
  goodPhotonSR_phibackground_copy__8->SetLineStyle(0);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetTitle("#phi^{#gamma}");
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetLabelSize(fig_6_x_label_size);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetTitleSize(0.06);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetTitleOffset(1.7);
  goodPhotonSR_phibackground_copy__8->GetXaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetTitle("Entries / 1.05");
  goodPhotonSR_phibackground_copy__8->GetYaxis()->CenterTitle(true);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetNdivisions(505);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetLabelSize(fig_6_y_label_size);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetTitleSize(0.05);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetTitleOffset(1.0);
  goodPhotonSR_phibackground_copy__8->GetYaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetLabelFont(42);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetLabelOffset(0.007);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetLabelSize(0.05);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetTitleSize(0.06);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetTitleOffset(1);
  goodPhotonSR_phibackground_copy__8->GetZaxis()->SetTitleFont(42);
  goodPhotonSR_phibackground_copy__8->Draw("sameaxis");
  goodPhotonSR_phi_1->Modified();
  goodPhotonSR_phi->cd();

  // ------------>Primitives in pad: goodPhotonSR_phi_2
  TPad *goodPhotonSR_phi_2 = new TPad("goodPhotonSR_phi_2", "goodPhotonSR_phi_2", 0, 0, 1, 0.3);
  goodPhotonSR_phi_2->Draw();
  goodPhotonSR_phi_2->cd();
  goodPhotonSR_phi_2->Range(-4.596232, -0.8571429, 4.505217, 2);
  goodPhotonSR_phi_2->SetFillColor(0);
  goodPhotonSR_phi_2->SetBorderMode(0);
  goodPhotonSR_phi_2->SetBorderSize(2);
  goodPhotonSR_phi_2->SetLeftMargin(0.16);
  goodPhotonSR_phi_2->SetRightMargin(0.15);
  goodPhotonSR_phi_2->SetTopMargin(0.05);
  goodPhotonSR_phi_2->SetBottomMargin(fig_6_ratio_bottom_margin);
  goodPhotonSR_phi_2->SetFrameFillStyle(0);
  goodPhotonSR_phi_2->SetFrameBorderMode(0);
  goodPhotonSR_phi_2->SetFrameFillStyle(0);
  goodPhotonSR_phi_2->SetFrameBorderMode(0);

  auto ratio_stack_goodPhotonSR_phi = new THStack();
  ratio_stack_goodPhotonSR_phi->SetName("ratio_stack_goodPhotonSR_phi");
  ratio_stack_goodPhotonSR_phi->SetTitle("");
  ratio_stack_goodPhotonSR_phi->SetMinimum(0);
  ratio_stack_goodPhotonSR_phi->SetMaximum(2);

  TH1F *ratio_stack_goodPhotonSR_phi_stack_9 = new TH1F("ratio_stack_goodPhotonSR_phi_stack_9", "", 6, -3.14, 3.14);
  ratio_stack_goodPhotonSR_phi_stack_9->SetMinimum(0);
  ratio_stack_goodPhotonSR_phi_stack_9->SetMaximum(2);
  ratio_stack_goodPhotonSR_phi_stack_9->SetDirectory(0);
  ratio_stack_goodPhotonSR_phi_stack_9->SetStats(0);
  ratio_stack_goodPhotonSR_phi_stack_9->SetLineStyle(0);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetTitle("#phi^{#gamma}");
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetLabelFont(42);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetLabelOffset(0.007);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetLabelSize(fig_6_x_ratio_label_size);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetTitleSize(fig_6_x_ratio_title_size);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetTitleOffset(1);
  ratio_stack_goodPhotonSR_phi_stack_9->GetXaxis()->SetTitleFont(42);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetTitle("Data/MC");
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->CenterTitle();
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->CenterTitle(true);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetNdivisions(505);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetLabelFont(42);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetLabelOffset(0.007);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetLabelSize(fig_6_y_ratio_label_size);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetTitleSize(fig_6_y_ratio_title_size);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetTitleOffset(0.5);
  ratio_stack_goodPhotonSR_phi_stack_9->GetYaxis()->SetTitleFont(42);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetLabelFont(42);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetLabelOffset(0.007);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetLabelSize(0.05);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetTitleSize(0.06);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetTitleOffset(1);
  ratio_stack_goodPhotonSR_phi_stack_9->GetZaxis()->SetTitleFont(42);
  ratio_stack_goodPhotonSR_phi->SetHistogram(ratio_stack_goodPhotonSR_phi_stack_9);

  TH1D *ratio_goodPhotonSR_phi_stack_1 = new TH1D("ratio_goodPhotonSR_phi_stack_1", "goodPhotonSR_phi", 6, -3.14, 3.14);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(1, 1.185125);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(2, 0.9748114);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(3, 0.9799148);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(4, 1.184878);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(5, 0.9737232);
  ratio_goodPhotonSR_phi_stack_1->SetBinContent(6, 0.9802972);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(1, 0.3765979);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(2, 0.3464099);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(3, 0.3478594);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(4, 0.3765184);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(5, 0.3460194);
  ratio_goodPhotonSR_phi_stack_1->SetBinError(6, 0.3479957);
  ratio_goodPhotonSR_phi_stack_1->SetEntries(51.50409);

  ci = 1486;
  color = new TColor(ci, 0, 1, 0, " ", 0);
  ratio_goodPhotonSR_phi_stack_1->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  ratio_goodPhotonSR_phi_stack_1->SetLineColor(ci);
  ratio_goodPhotonSR_phi_stack_1->SetMarkerStyle(20);
  ratio_goodPhotonSR_phi_stack_1->GetXaxis()->SetRange(1, 6);
  ratio_goodPhotonSR_phi_stack_1->GetXaxis()->SetLabelFont(42);
  ratio_goodPhotonSR_phi_stack_1->GetXaxis()->SetTitleOffset(1);
  ratio_goodPhotonSR_phi_stack_1->GetXaxis()->SetTitleFont(42);
  ratio_goodPhotonSR_phi_stack_1->GetYaxis()->SetLabelFont(42);
  ratio_goodPhotonSR_phi_stack_1->GetYaxis()->SetTitleFont(42);
  ratio_goodPhotonSR_phi_stack_1->GetZaxis()->SetLabelFont(42);
  ratio_goodPhotonSR_phi_stack_1->GetZaxis()->SetTitleOffset(1);
  ratio_goodPhotonSR_phi_stack_1->GetZaxis()->SetTitleFont(42);
  ratio_stack_goodPhotonSR_phi->Add(ratio_goodPhotonSR_phi_stack_1, "");
  ratio_stack_goodPhotonSR_phi->Draw("pe1");
  TLine *line = new TLine(-3.14, 1, 3.14, 1);
  line->SetLineStyle(2);
  line->Draw();

  TH1D *ratio_uncertainty_goodPhotonSR_phi__9 = new TH1D("ratio_uncertainty_goodPhotonSR_phi__9", "goodPhotonSR_phi", 6, -3.14, 3.14);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(0, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(1, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(2, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(3, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(4, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(5, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(6, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinContent(7, 1);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(0, 1.074038);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(1, 0.3282625);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(2, 0.3291851);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(3, 0.3283824);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(4, 0.3282607);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(5, 0.3291767);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(6, 0.3283836);
  ratio_uncertainty_goodPhotonSR_phi__9->SetBinError(7, 0.6525095);
  ratio_uncertainty_goodPhotonSR_phi__9->SetEntries(55.56393);

  ci = 1557;
  color = new TColor(ci, 0, 0, 0, " ", 0.3);
  ratio_uncertainty_goodPhotonSR_phi__9->SetFillColorAlpha(ci, 0.5);
  ratio_uncertainty_goodPhotonSR_phi__9->SetFillStyle(3004);
  ratio_uncertainty_goodPhotonSR_phi__9->SetMarkerStyle(20);
  ratio_uncertainty_goodPhotonSR_phi__9->SetMarkerSize(0);
  ratio_uncertainty_goodPhotonSR_phi__9->GetXaxis()->SetRange(1, 6);
  ratio_uncertainty_goodPhotonSR_phi__9->GetXaxis()->SetLabelFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->GetXaxis()->SetTitleOffset(1);
  ratio_uncertainty_goodPhotonSR_phi__9->GetXaxis()->SetTitleFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->GetYaxis()->SetLabelFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->GetYaxis()->SetTitleFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->GetZaxis()->SetLabelFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->GetZaxis()->SetTitleOffset(1);
  ratio_uncertainty_goodPhotonSR_phi__9->GetZaxis()->SetTitleFont(42);
  ratio_uncertainty_goodPhotonSR_phi__9->Draw("same e2");
  goodPhotonSR_phi_2->Modified();
  goodPhotonSR_phi->cd();
  // auto tex = new TLatex(0.16, 0.95, "#bf{CMS} #it{Preliminary}");
  auto tex = new TLatex(0.16, 0.95, "#bf{CMS}");
  tex->SetNDC();
  tex->SetTextFont(42);
  tex->SetTextSize(0.05);
  tex->SetLineWidth(2);
  tex->Draw();

  tex = new TLatex(0.45, 0.95, "#scale[0.8]{PbPb, 1.65 nb^{-1} (#sqrt{s_{NN}} = 5.02 TeV)}");
  tex->SetNDC();
  tex->SetTextFont(42);
  tex->SetTextSize(0.05);
  tex->SetLineWidth(2);
  tex->Draw();
  goodPhotonSR_phi->Modified();
  goodPhotonSR_phi->cd();
  goodPhotonSR_phi->SetSelected(goodPhotonSR_phi);
  goodPhotonSR_phi->SaveAs("figures/Figure_006_e.pdf");
}
