#ifdef __CLING__
#pragma cling optimize(0)
#endif

#include "style.h"

void plot_fig_6_f() {
  gROOT->SetBatch(kTRUE);
  //=========Macro generated from canvas: diphotonSR_mass/diphotonSR_mass
  //=========  (Sun Mar 31 12:51:37 2024) by ROOT version 6.26/08
  TCanvas *diphotonSR_mass = new TCanvas("diphotonSR_mass", "diphotonSR_mass", 0, 0, 800, 600);
  gStyle->SetOptFit(1);
  gStyle->SetOptStat(0);
  gStyle->SetOptTitle(0);
  diphotonSR_mass->SetHighLightColor(2);
  diphotonSR_mass->Range(0, 0, 1, 1);
  diphotonSR_mass->SetFillColor(0);
  diphotonSR_mass->SetBorderMode(0);
  diphotonSR_mass->SetBorderSize(2);
  diphotonSR_mass->SetTickx(1);
  diphotonSR_mass->SetTicky(1);
  diphotonSR_mass->SetLeftMargin(0.16);
  diphotonSR_mass->SetRightMargin(0.15);
  diphotonSR_mass->SetTopMargin(0.06);
  diphotonSR_mass->SetBottomMargin(0.3);
  diphotonSR_mass->SetFrameFillStyle(0);
  diphotonSR_mass->SetFrameBorderMode(0);

  // ------------>Primitives in pad: diphotonSR_mass_1
  TPad *diphotonSR_mass_1 = new TPad("diphotonSR_mass_1", "diphotonSR_mass_1", 0, 0.3, 1, 1);
  diphotonSR_mass_1->Draw();
  diphotonSR_mass_1->cd();
  diphotonSR_mass_1->Range(-5.797101, -1.069943, 30.43478, 2.509624);
  diphotonSR_mass_1->SetFillColor(0);
  diphotonSR_mass_1->SetBorderMode(0);
  diphotonSR_mass_1->SetBorderSize(2);
  diphotonSR_mass_1->SetLogy();
  diphotonSR_mass_1->SetLeftMargin(0.16);
  diphotonSR_mass_1->SetRightMargin(0.15);
  diphotonSR_mass_1->SetBottomMargin(0.05);
  diphotonSR_mass_1->SetFrameFillStyle(0);
  diphotonSR_mass_1->SetFrameBorderMode(0);
  diphotonSR_mass_1->SetFrameFillStyle(0);
  diphotonSR_mass_1->SetFrameLineWidth(2);
  diphotonSR_mass_1->SetFrameBorderMode(0);
  diphotonSR_mass_1->SetFrameBorderSize(2);

  THStack *diphotonSR_massbackground = new THStack();
  diphotonSR_massbackground->SetName("diphotonSR_massbackground");
  diphotonSR_massbackground->SetTitle("");
  diphotonSR_massbackground->SetMinimum(0.2);
  diphotonSR_massbackground->SetMaximum(100);

  TH1F *diphotonSR_massbackground_stack_16 = new TH1F("diphotonSR_massbackground_stack_16", "", 10, 0, 25);
  diphotonSR_massbackground_stack_16->SetMinimum(0.08512504);
  diphotonSR_massbackground_stack_16->SetMaximum(153.9794);
  diphotonSR_massbackground_stack_16->SetDirectory(0);
  diphotonSR_massbackground_stack_16->SetStats(0);
  diphotonSR_massbackground_stack_16->SetLineStyle(0);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetTitle("m^{#gamma#gamma} (GeV)");
  diphotonSR_massbackground_stack_16->GetXaxis()->SetLabelFont(42);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetLabelSize(0.0);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetTitleSize(fig_6_x_title_size);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetTitleOffset(1.7);
  diphotonSR_massbackground_stack_16->GetXaxis()->SetTitleFont(42);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetTitle("Events / 5 (GeV^{-1})");
  diphotonSR_massbackground_stack_16->GetYaxis()->CenterTitle(true);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetNdivisions(505);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetLabelFont(42);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetLabelSize(0.06);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetTitleSize(fig_6_y_title_size);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetTitleOffset(1.0);
  diphotonSR_massbackground_stack_16->GetYaxis()->SetTitleFont(42);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetLabelFont(42);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetLabelSize(0.05);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetTitleSize(0.06);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetTitleOffset(1);
  diphotonSR_massbackground_stack_16->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground->SetHistogram(diphotonSR_massbackground_stack_16);

  TH1D *diphotonSR_mass_stack_1 = new TH1D("diphotonSR_mass_stack_1", "diphotonSR_mass", 10, 0, 50);
  diphotonSR_mass_stack_1->SetBinContent(2, 7.947385);
  diphotonSR_mass_stack_1->SetBinContent(3, 1.60381);
  diphotonSR_mass_stack_1->SetBinContent(4, 0.3830363);
  diphotonSR_mass_stack_1->SetBinContent(5, 0.1136753);
  diphotonSR_mass_stack_1->SetBinContent(6, 0.02965442);
  diphotonSR_mass_stack_1->SetBinContent(7, 0.01235601);
  diphotonSR_mass_stack_1->SetBinContent(8, 0.004942403);
  diphotonSR_mass_stack_1->SetBinContent(9, 0.007413605);
  diphotonSR_mass_stack_1->SetBinContent(10, 0.002471202);
  diphotonSR_mass_stack_1->SetBinError(2, 0.1401413);
  diphotonSR_mass_stack_1->SetBinError(3, 0.06295505);
  diphotonSR_mass_stack_1->SetBinError(4, 0.03076621);
  diphotonSR_mass_stack_1->SetBinError(5, 0.01676051);
  diphotonSR_mass_stack_1->SetBinError(6, 0.008560494);
  diphotonSR_mass_stack_1->SetBinError(7, 0.005525775);
  diphotonSR_mass_stack_1->SetBinError(8, 0.003494807);
  diphotonSR_mass_stack_1->SetBinError(9, 0.004280247);
  diphotonSR_mass_stack_1->SetBinError(10, 0.002471202);
  diphotonSR_mass_stack_1->SetEntries(4089);
  diphotonSR_mass_stack_1->SetDirectory(0);

  Int_t ci;       // for color index setting
  TColor *color;  // for color definition with alpha
  ci = TColor::GetColor("#6699ff");
  diphotonSR_mass_stack_1->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  diphotonSR_mass_stack_1->SetLineColor(ci);
  diphotonSR_mass_stack_1->SetMarkerStyle(20);
  diphotonSR_mass_stack_1->GetXaxis()->SetRange(1, 10);
  diphotonSR_mass_stack_1->GetXaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_1->GetXaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_1->GetXaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_1->GetYaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_1->GetYaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_1->GetZaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_1->GetZaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_1->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground->Add(diphotonSR_mass_stack_1, "");

  TH1D *diphotonSR_mass_stack_2 = new TH1D("diphotonSR_mass_stack_2", "diphotonSR_mass", 10, 0, 50);
  diphotonSR_mass_stack_2->SetBinContent(2, 0.4024781);
  diphotonSR_mass_stack_2->SetBinContent(3, 0.3449812);
  diphotonSR_mass_stack_2->SetBinError(2, 0.1521224);
  diphotonSR_mass_stack_2->SetBinError(3, 0.140838);
  diphotonSR_mass_stack_2->SetEntries(13);
  diphotonSR_mass_stack_2->SetDirectory(0);

  ci = TColor::GetColor("#ffff00");
  diphotonSR_mass_stack_2->SetFillColor(ci);

  ci = TColor::GetColor("#ffff00");
  diphotonSR_mass_stack_2->SetLineColor(ci);
  diphotonSR_mass_stack_2->SetMarkerStyle(20);
  diphotonSR_mass_stack_2->SetMarkerSize(0);
  diphotonSR_mass_stack_2->GetXaxis()->SetRange(1, 10);
  diphotonSR_mass_stack_2->GetXaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_2->GetXaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_2->GetXaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_2->GetYaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_2->GetYaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_2->GetZaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_2->GetZaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_2->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground->Add(diphotonSR_mass_stack_2, "");

  TH1D *diphotonSR_mass_stack_3 = new TH1D("diphotonSR_mass_stack_3", "diphotonSR_mass", 10, 0, 50);
  diphotonSR_mass_stack_3->SetBinContent(2, 0.7940088);
  diphotonSR_mass_stack_3->SetBinContent(3, 0.07218262);
  diphotonSR_mass_stack_3->SetBinContent(4, 0.07218262);
  diphotonSR_mass_stack_3->SetBinContent(5, 0.07218262);
  diphotonSR_mass_stack_3->SetBinContent(6, 0.07218262);
  diphotonSR_mass_stack_3->SetBinContent(7, 0.07218262);
  diphotonSR_mass_stack_3->SetBinError(2, 0.2394027);
  diphotonSR_mass_stack_3->SetBinError(3, 0.07218262);
  diphotonSR_mass_stack_3->SetBinError(4, 0.07218262);
  diphotonSR_mass_stack_3->SetBinError(5, 0.07218262);
  diphotonSR_mass_stack_3->SetBinError(6, 0.07218262);
  diphotonSR_mass_stack_3->SetBinError(7, 0.07218262);
  diphotonSR_mass_stack_3->SetEntries(16);
  diphotonSR_mass_stack_3->SetDirectory(0);

  ci = TColor::GetColor("#ffff00");
  diphotonSR_mass_stack_3->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  diphotonSR_mass_stack_3->SetLineColor(ci);
  diphotonSR_mass_stack_3->SetMarkerStyle(20);
  diphotonSR_mass_stack_3->SetMarkerSize(0);
  diphotonSR_mass_stack_3->GetXaxis()->SetRange(1, 10);
  diphotonSR_mass_stack_3->GetXaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_3->GetXaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_3->GetXaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_3->GetYaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_3->GetYaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_3->GetZaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_3->GetZaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_3->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground->Add(diphotonSR_mass_stack_3, "");

  TH1D *diphotonSR_mass_stack_4 = new TH1D("diphotonSR_mass_stack_4", "diphotonSR_mass", 10, 0, 50);
  diphotonSR_mass_stack_4->SetBinContent(2, 8.495196);
  diphotonSR_mass_stack_4->SetBinContent(3, 2.714843);
  diphotonSR_mass_stack_4->SetBinContent(4, 0.9275713);
  diphotonSR_mass_stack_4->SetBinContent(5, 0.3789468);
  diphotonSR_mass_stack_4->SetBinContent(6, 0.1413981);
  diphotonSR_mass_stack_4->SetBinContent(7, 0.07918292);
  diphotonSR_mass_stack_4->SetBinContent(8, 0.02827961);
  diphotonSR_mass_stack_4->SetBinContent(9, 0.02827961);
  diphotonSR_mass_stack_4->SetBinContent(10, 0.005655923);
  diphotonSR_mass_stack_4->SetBinContent(11, 0.02262369);
  diphotonSR_mass_stack_4->SetBinError(2, 0.2191989);
  diphotonSR_mass_stack_4->SetBinError(3, 0.1239151);
  diphotonSR_mass_stack_4->SetBinError(4, 0.07243115);
  diphotonSR_mass_stack_4->SetBinError(5, 0.04629572);
  diphotonSR_mass_stack_4->SetBinError(6, 0.02827961);
  diphotonSR_mass_stack_4->SetBinError(7, 0.02116253);
  diphotonSR_mass_stack_4->SetBinError(8, 0.01264703);
  diphotonSR_mass_stack_4->SetBinError(9, 0.01264703);
  diphotonSR_mass_stack_4->SetBinError(10, 0.005655923);
  diphotonSR_mass_stack_4->SetBinError(11, 0.01131185);
  diphotonSR_mass_stack_4->SetEntries(2267);
  diphotonSR_mass_stack_4->SetDirectory(0);

  ci = TColor::GetColor("#ff9933");
  diphotonSR_mass_stack_4->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  diphotonSR_mass_stack_4->SetLineColor(ci);
  diphotonSR_mass_stack_4->SetMarkerStyle(20);
  diphotonSR_mass_stack_4->GetXaxis()->SetRange(1, 10);
  diphotonSR_mass_stack_4->GetXaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_4->GetXaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_4->GetXaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_4->GetYaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_4->GetYaxis()->SetTitleFont(42);
  diphotonSR_mass_stack_4->GetZaxis()->SetLabelFont(42);
  diphotonSR_mass_stack_4->GetZaxis()->SetTitleOffset(1);
  diphotonSR_mass_stack_4->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground->Add(diphotonSR_mass_stack_4, "");
  diphotonSR_massbackground->Draw("hist");
  diphotonSR_massbackground->GetXaxis()->SetRangeUser(5, 25);

  
  Double_t Graph0_fx3006[10] = {2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5};
  Double_t Graph0_fy3006[10] = {0, 19, 6, 1, 0, 0, 0, 0, 0, 0};
  Double_t Graph0_felx3006[10] = {2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5};
  Double_t Graph0_fely3006[10] = {0, 4.320219, 2.379931, 0.8272462, 0, 0, 0, 0, 0, 0};
  Double_t Graph0_fehx3006[10] = {2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5};
  Double_t Graph0_fehy3006[10] = {1.841022, 5.435196, 3.583642, 2.299527, 1.841022, 1.841022, 1.841022, 1.841022, 1.841022, 1.841022};
  TGraphAsymmErrors *grae =
      new TGraphAsymmErrors(10, Graph0_fx3006, Graph0_fy3006, Graph0_felx3006, Graph0_fehx3006, Graph0_fely3006, Graph0_fehy3006);
  grae->SetName("Graph0");
  grae->SetTitle("Graph");
  grae->SetFillStyle(1000);
  grae->SetMarkerStyle(20);

  TH1F *Graph_Graph03006 = new TH1F("Graph_Graph03006", "Graph", 100, 0, 52);
  Graph_Graph03006->SetMinimum(0.02687872);
  Graph_Graph03006->SetMaximum(26.87872);
  Graph_Graph03006->SetDirectory(0);
  Graph_Graph03006->SetStats(0);
  Graph_Graph03006->SetLineStyle(0);
  Graph_Graph03006->GetXaxis()->SetLabelFont(42);
  Graph_Graph03006->GetXaxis()->SetLabelOffset(0.007);
  Graph_Graph03006->GetXaxis()->SetLabelSize(0.05);
  Graph_Graph03006->GetXaxis()->SetTitleSize(0.06);
  Graph_Graph03006->GetXaxis()->SetTitleOffset(0.9);
  Graph_Graph03006->GetXaxis()->SetTitleFont(42);
  Graph_Graph03006->GetYaxis()->SetLabelFont(42);
  Graph_Graph03006->GetYaxis()->SetLabelOffset(0.007);
  Graph_Graph03006->GetYaxis()->SetLabelSize(0.05);
  Graph_Graph03006->GetYaxis()->SetTitleSize(0.06);
  Graph_Graph03006->GetYaxis()->SetTitleOffset(1.25);
  Graph_Graph03006->GetYaxis()->SetTitleFont(42);
  Graph_Graph03006->GetZaxis()->SetLabelFont(42);
  Graph_Graph03006->GetZaxis()->SetLabelOffset(0.007);
  Graph_Graph03006->GetZaxis()->SetLabelSize(0.05);
  Graph_Graph03006->GetZaxis()->SetTitleSize(0.06);
  Graph_Graph03006->GetZaxis()->SetTitleOffset(1);
  Graph_Graph03006->GetZaxis()->SetTitleFont(42);
  grae->SetHistogram(Graph_Graph03006);

  grae->Draw("pe");

  TH1D *backgrounds_unc_diphotonSR_mass__16 = new TH1D("backgrounds_unc_diphotonSR_mass__16", "diphotonSR_mass", 10, 0, 50);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(2, 17.63907);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(3, 4.735817);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(4, 1.38279);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(5, 0.5648047);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(6, 0.2432351);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(7, 0.1637215);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(8, 0.03322202);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(9, 0.03569322);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(10, 0.008127124);
  backgrounds_unc_diphotonSR_mass__16->SetBinContent(11, 0.02262369);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(2, 4.075202);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(3, 1.109416);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(4, 0.3354903);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(5, 0.1565563);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(6, 0.09598483);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(7, 0.08430117);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(8, 0.01518377);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(9, 0.01567363);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(10, 0.006449058);
  backgrounds_unc_diphotonSR_mass__16->SetBinError(11, 0.01131185);
  backgrounds_unc_diphotonSR_mass__16->SetEntries(6385);

  ci = 1560;
  color = new TColor(ci, 0, 0, 0, " ", 0.3);
  backgrounds_unc_diphotonSR_mass__16->SetFillColorAlpha(ci, 0.5);
  backgrounds_unc_diphotonSR_mass__16->SetFillStyle(3004);
  backgrounds_unc_diphotonSR_mass__16->SetMarkerStyle(20);
  backgrounds_unc_diphotonSR_mass__16->SetMarkerSize(0);
  backgrounds_unc_diphotonSR_mass__16->GetXaxis()->SetRange(1, 10);
  backgrounds_unc_diphotonSR_mass__16->GetXaxis()->SetLabelFont(42);
  backgrounds_unc_diphotonSR_mass__16->GetXaxis()->SetTitleOffset(1);
  backgrounds_unc_diphotonSR_mass__16->GetXaxis()->SetTitleFont(42);
  backgrounds_unc_diphotonSR_mass__16->GetYaxis()->SetLabelFont(42);
  backgrounds_unc_diphotonSR_mass__16->GetYaxis()->SetTitleFont(42);
  backgrounds_unc_diphotonSR_mass__16->GetZaxis()->SetLabelFont(42);
  backgrounds_unc_diphotonSR_mass__16->GetZaxis()->SetTitleOffset(1);
  backgrounds_unc_diphotonSR_mass__16->GetZaxis()->SetTitleFont(42);
  backgrounds_unc_diphotonSR_mass__16->Draw("same e2");

  auto leg = get_lbl_legend();
  // leg->Draw();
  TH1F *diphotonSR_massbackground_copy__17 = new TH1F("diphotonSR_massbackground_copy__17", "", 10, 0, 25);
  diphotonSR_massbackground_copy__17->SetMinimum(0.08512504);
  diphotonSR_massbackground_copy__17->SetMaximum(153.9794);
  diphotonSR_massbackground_copy__17->SetDirectory(0);
  diphotonSR_massbackground_copy__17->SetStats(0);
  diphotonSR_massbackground_copy__17->SetLineStyle(0);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetTitle("m^{#gamma#gamma} (GeV)");
  diphotonSR_massbackground_copy__17->GetXaxis()->SetLabelFont(42);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetLabelSize(fig_6_x_label_size);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetTitleSize(0.06);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetTitleOffset(1.7);
  diphotonSR_massbackground_copy__17->GetXaxis()->SetTitleFont(42);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetTitle("Events / 5 GeV");
  diphotonSR_massbackground_copy__17->GetYaxis()->CenterTitle(true);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetNdivisions(505);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetLabelFont(42);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetLabelSize(fig_6_y_label_size);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetTitleSize(0.05);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetTitleOffset(1.0);
  diphotonSR_massbackground_copy__17->GetYaxis()->SetTitleFont(42);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetLabelFont(42);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetLabelOffset(0.007);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetLabelSize(0.05);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetTitleSize(0.06);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetTitleOffset(1);
  diphotonSR_massbackground_copy__17->GetZaxis()->SetTitleFont(42);
  diphotonSR_massbackground_copy__17->Draw("sameaxis");
  diphotonSR_mass_1->Modified();
  diphotonSR_mass->cd();

  // ------------>Primitives in pad: diphotonSR_mass_2
  TPad *diphotonSR_mass_2 = new TPad("diphotonSR_mass_2", "diphotonSR_mass_2", 0, 0, 1, 0.3);
  diphotonSR_mass_2->Draw();
  diphotonSR_mass_2->cd();
  diphotonSR_mass_2->Range(-5.797101, -0.8571429, 30.43478, 2);
  diphotonSR_mass_2->SetFillColor(0);
  diphotonSR_mass_2->SetBorderMode(0);
  diphotonSR_mass_2->SetBorderSize(2);
  diphotonSR_mass_2->SetLeftMargin(0.16);
  diphotonSR_mass_2->SetRightMargin(0.15);
  diphotonSR_mass_2->SetTopMargin(0.05);
  diphotonSR_mass_2->SetBottomMargin(fig_6_ratio_bottom_margin);
  diphotonSR_mass_2->SetFrameFillStyle(0);
  diphotonSR_mass_2->SetFrameBorderMode(0);
  diphotonSR_mass_2->SetFrameFillStyle(0);
  diphotonSR_mass_2->SetFrameBorderMode(0);

  auto ratio_stack_diphotonSR_mass = new THStack();
  ratio_stack_diphotonSR_mass->SetName("ratio_stack_diphotonSR_mass");
  ratio_stack_diphotonSR_mass->SetTitle("");
  ratio_stack_diphotonSR_mass->SetMinimum(0);
  ratio_stack_diphotonSR_mass->SetMaximum(2);

  TH1F *ratio_stack_diphotonSR_mass_stack_18 = new TH1F("ratio_stack_diphotonSR_mass_stack_18", "", 10, 0, 25);
  ratio_stack_diphotonSR_mass_stack_18->SetMinimum(0);
  ratio_stack_diphotonSR_mass_stack_18->SetMaximum(2);
  ratio_stack_diphotonSR_mass_stack_18->SetDirectory(0);
  ratio_stack_diphotonSR_mass_stack_18->SetStats(0);
  ratio_stack_diphotonSR_mass_stack_18->SetLineStyle(0);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetTitle("m^{#gamma#gamma} (GeV)");
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetLabelFont(42);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetLabelOffset(0.007);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetLabelSize(fig_6_x_ratio_label_size);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetTitleSize(fig_6_x_ratio_title_size);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetTitleOffset(1);
  ratio_stack_diphotonSR_mass_stack_18->GetXaxis()->SetTitleFont(42);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetTitle("Data/MC");
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->CenterTitle();
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->CenterTitle(true);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetNdivisions(505);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetLabelFont(42);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetLabelOffset(0.007);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetLabelSize(fig_6_y_ratio_label_size);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetTitleSize(fig_6_y_ratio_title_size);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetTitleOffset(0.5);
  ratio_stack_diphotonSR_mass_stack_18->GetYaxis()->SetTitleFont(42);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetLabelFont(42);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetLabelOffset(0.007);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetLabelSize(0.05);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetTitleSize(0.06);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetTitleOffset(1);
  ratio_stack_diphotonSR_mass_stack_18->GetZaxis()->SetTitleFont(42);
  ratio_stack_diphotonSR_mass->SetHistogram(ratio_stack_diphotonSR_mass_stack_18);

  TH1D *ratio_diphotonSR_mass_stack_1 = new TH1D("ratio_diphotonSR_mass_stack_1", "diphotonSR_mass", 10, 0, 50);
  ratio_diphotonSR_mass_stack_1->SetBinContent(2, 1.077154);
  ratio_diphotonSR_mass_stack_1->SetBinContent(3, 1.266941);
  ratio_diphotonSR_mass_stack_1->SetBinContent(4, 0.7231755);
  ratio_diphotonSR_mass_stack_1->SetBinContent(5, 0.0);
  ratio_diphotonSR_mass_stack_1->SetBinError(2, 0.2482314);
  ratio_diphotonSR_mass_stack_1->SetBinError(3, 0.5202867);
  ratio_diphotonSR_mass_stack_1->SetBinError(4, 0.7253287);
  ratio_diphotonSR_mass_stack_1->SetBinError(5, 1.84);
  ratio_diphotonSR_mass_stack_1->SetEntries(10.95986);

  ci = 1492;
  color = new TColor(ci, 0, 1, 0, " ", 0);
  ratio_diphotonSR_mass_stack_1->SetFillColor(ci);

  ci = TColor::GetColor("#000000");
  ratio_diphotonSR_mass_stack_1->SetLineColor(ci);
  ratio_diphotonSR_mass_stack_1->SetMarkerStyle(20);
  ratio_diphotonSR_mass_stack_1->GetXaxis()->SetRange(1, 10);
  ratio_diphotonSR_mass_stack_1->GetXaxis()->SetLabelFont(42);
  ratio_diphotonSR_mass_stack_1->GetXaxis()->SetTitleOffset(1);
  ratio_diphotonSR_mass_stack_1->GetXaxis()->SetTitleFont(42);
  ratio_diphotonSR_mass_stack_1->GetYaxis()->SetLabelFont(42);
  ratio_diphotonSR_mass_stack_1->GetYaxis()->SetTitleFont(42);
  ratio_diphotonSR_mass_stack_1->GetZaxis()->SetLabelFont(42);
  ratio_diphotonSR_mass_stack_1->GetZaxis()->SetTitleOffset(1);
  ratio_diphotonSR_mass_stack_1->GetZaxis()->SetTitleFont(42);
  ratio_stack_diphotonSR_mass->Add(ratio_diphotonSR_mass_stack_1, "");
  ratio_stack_diphotonSR_mass->Draw("pe1");
  ratio_stack_diphotonSR_mass->GetXaxis()->SetRangeUser(5, 25);
  TLine *line = new TLine(5, 1, 25, 1);
  line->SetLineStyle(2);
  line->Draw();

  TH1D *ratio_uncertainty_diphotonSR_mass__18 = new TH1D("ratio_uncertainty_diphotonSR_mass__18", "diphotonSR_mass", 10, 0, 50);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(2, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(3, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(4, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(5, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(6, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(7, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(8, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(9, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(10, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinContent(11, 1);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(2, 0.3267297);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(3, 0.3312946);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(4, 0.3431141);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(5, 0.392001);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(6, 0.5580734);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(7, 0.7281868);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(8, 0.6463512);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(9, 0.6210105);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(10, 1.122211);
  ratio_uncertainty_diphotonSR_mass__18->SetBinError(11, 0.7071068);
  ratio_uncertainty_diphotonSR_mass__18->SetEntries(23.87702);

  ci = 1560;
  color = new TColor(ci, 0, 0, 0, " ", 0.3);
  ratio_uncertainty_diphotonSR_mass__18->SetFillColorAlpha(ci, 0.5);
  ratio_uncertainty_diphotonSR_mass__18->SetFillStyle(3004);
  ratio_uncertainty_diphotonSR_mass__18->SetMarkerStyle(20);
  ratio_uncertainty_diphotonSR_mass__18->SetMarkerSize(0);
  ratio_uncertainty_diphotonSR_mass__18->GetXaxis()->SetRange(1, 10);
  ratio_uncertainty_diphotonSR_mass__18->GetXaxis()->SetLabelFont(42);
  ratio_uncertainty_diphotonSR_mass__18->GetXaxis()->SetTitleOffset(1);
  ratio_uncertainty_diphotonSR_mass__18->GetXaxis()->SetTitleFont(42);
  ratio_uncertainty_diphotonSR_mass__18->GetYaxis()->SetLabelFont(42);
  ratio_uncertainty_diphotonSR_mass__18->GetYaxis()->SetTitleFont(42);
  ratio_uncertainty_diphotonSR_mass__18->GetZaxis()->SetLabelFont(42);
  ratio_uncertainty_diphotonSR_mass__18->GetZaxis()->SetTitleOffset(1);
  ratio_uncertainty_diphotonSR_mass__18->GetZaxis()->SetTitleFont(42);
  ratio_uncertainty_diphotonSR_mass__18->Draw("same e2");
  diphotonSR_mass_2->Modified();
  diphotonSR_mass->cd();
  // auto tex = new TLatex(0.16, 0.95, "#bf{CMS} #it{Preliminary}");
  auto tex = new TLatex(0.16, 0.95, "#bf{CMS}");
  tex->SetNDC();
  tex->SetTextFont(42);
  tex->SetTextSize(0.05);
  tex->SetLineWidth(2);
  tex->Draw();

  tex = new TLatex(0.45, 0.95, "#scale[0.8]{PbPb, 1.65 nb^{-1} (#sqrt{s_{NN}} = 5.02 TeV)}");
  tex->SetNDC();
  tex->SetTextFont(42);
  tex->SetTextSize(0.05);
  tex->SetLineWidth(2);
  tex->Draw();
  diphotonSR_mass->Modified();
  diphotonSR_mass->cd();
  diphotonSR_mass->SetSelected(diphotonSR_mass);
  diphotonSR_mass->SaveAs("figures/Figure_006_f.pdf");
}
